
services:
  client:
    build: ./client
    container_name: music-frontend
    ports:
      - "5173:5173"
    depends_on:
      - server

  server:
    build: ./server
    container_name: music-backend
    ports:
      - "8070:8070"